### PR TITLE
Update ZoneParser.cs

### PR DESCRIPTION
**Pull request by gabbermatt**
Changed some zone names so the map will auto-switch for them. I'm sure there's more so I'll try to update as I figure them out

### CODE REVIEW

**Comment by gabbermatt** [comment]
Also, please let me know if I did this wrong, it's my first PR

**Comment by smasherprog** [comment]
is this a PQ thing? it looks like it. We can leave the old code and add the new mapping. Both can exist

**Comment by gabbermatt** [comment]
Oh, yes it's for PQ my bad

**Comment by smasherprog** [comment]
Pq is fine, but the old names are valid for p99 and new are for PQ. But both can be in code at the same time without any of checks.

**Comment by smasherprog** [comment]
as soon as you update the PR ill approve it

**Comment by gabbermatt** [comment]
Ok should be fixed now

**Pull request merged**
